# Site settings
title: Nashville
client:
  name: Nashville Convention & Visitors Corp
  link: https://www.visitmusiccity.com/
core-se-link: https://www.secretescapes.com/current-sales
description: >
  Honky tonks and hot chicken, songwriters and artisans – Nashville is for many, a place for dreams, a siren song to artists and creatives across the USA. And what does that mean for your travels? A hotbed of burgeoning scenes, from art to artisan crafts, envelope-pushing foodie culture and classic southern eats, and then the big ticket – the music. It echoes from dance halls and dive bars across the city, a soundtrack to a feeling of limitless opportunity. Unpick your Nashville escape here.

# file paths
url:     "http://mp.secretescapes.com" # the base hostname & protocol for your site
baseurl: "/nashville" # the subpath of your site, e.g. /blog/
img:     "/nashville/_assets/img"
css:     "/nashville/_assets/css"
js:      "/nashville/_assets/js"


# Build settings
markdown: kramdown
exclude: [node_modules, gulpfile.js, package.json, package-lock.json, js/script.js]
keep_files: [_assets]
sass:
    sass_dir: css
    style: compressed